# Generated by Django 2.2.5 on 2019-09-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='posts.Topic'),
        ),
    ]
